"""empty message

Revision ID: 16ecf5e03263
Revises: dad490e73c09
Create Date: 2025-02-26 01:28:13.006088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16ecf5e03263'
down_revision = 'dad490e73c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottom_detail', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_constraint('bottom_detail_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Clothing', ['clothing_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('top_detail', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_constraint('top_detail_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Clothing', ['clothing_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('top_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('top_detail_ibfk_1', 'clothing', ['clothing_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)

    with op.batch_alter_table('bottom_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bottom_detail_ibfk_1', 'clothing', ['clothing_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('id', ['id'], unique=True)

    op.create_table('clothing',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('color', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('company', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('gender', mysql.ENUM('Men', 'Women'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    op.create_table('role_user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='role_user_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='role_user_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('roles_users')
    op.drop_table('Clothing')
    # ### end Alembic commands ###
