"""Initial migration

Revision ID: 8a2428f917b4
Revises: 
Create Date: 2025-03-03 13:03:48.775550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a2428f917b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottom_detail', schema=None) as batch_op:
        batch_op.drop_constraint('bottom_detail_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Clothing', ['clothing_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('top_detail', schema=None) as batch_op:
        batch_op.drop_constraint('top_detail_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Clothing', ['clothing_id'], ['id'], ondelete='CASCADE')

    op.add_column('clothing', sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('top_detail_ibfk_1', 'clothing', ['clothing_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bottom_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bottom_detail_ibfk_1', 'clothing', ['clothing_id'], ['id'], ondelete='CASCADE')

    op.add_column('clothing', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
