"""Added stock column to Clothing table

Revision ID: bbcf62560c57
Revises: 8a2428f917b4
Create Date: 2025-03-07 20:32:11.345970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbcf62560c57'
down_revision = '8a2428f917b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bottom_detail', schema=None) as batch_op:
        batch_op.drop_constraint('bottom_detail_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Clothing', ['clothing_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('top_detail', schema=None) as batch_op:
        batch_op.drop_constraint('top_detail_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Clothing', ['clothing_id'], ['id'], ondelete='CASCADE')

    op.add_column('clothing', sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('top_detail_ibfk_1', 'clothing', ['clothing_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bottom_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bottom_detail_ibfk_1', 'clothing', ['clothing_id'], ['id'], ondelete='CASCADE')

    op.create_table('clothing',
    sa.Column('id', mysql.CHAR(length=32), nullable=False),
    sa.Column('color', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('company', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('gender', mysql.ENUM('Men', 'Women'), nullable=False),
    sa.Column('price', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Clothing')
    # ### end Alembic commands ###
