"""empty message

Revision ID: dad490e73c09
Revises: 
Create Date: 2025-02-25 22:06:54.782308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dad490e73c09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.alter_column('id',
                              type=sa.Integer,
                              nullable=False,
                              existing_nullable=True,
                              existing_type=sa.Integer(),
                              existing_autoincrement=True,
                              )

    with op.batch_alter_table('bottom_detail', schema=None) as batch_op:
        batch_op.alter_column('id',
                              type=sa.Integer,
                              existing_type=mysql.INTEGER(),
                              nullable=False,
                              )
        batch_op.drop_constraint('bottom_detail_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Clothing', ['clothing_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('top_detail', schema=None) as batch_op:
        batch_op.alter_column('id',
                              type=sa.Integer,
                              existing_type=mysql.INTEGER(),
                              nullable=False,
                              )
        batch_op.drop_constraint('top_detail_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Clothing', ['clothing_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('top_detail_ibfk_1', 'clothing', ['clothing_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('bottom_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bottom_detail_ibfk_1', 'clothing', ['clothing_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)

    op.create_table('clothing',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('color', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('company', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('gender', mysql.ENUM('Men', 'Women'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    op.drop_table('role_user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('Clothing')
    # ### end Alembic commands ###
